name: Deploy CSS Layout Designer to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages subfolder (css-layout)
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          set -e
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --depth 1 https://x-access-token:${GH_PAGES_TOKEN}@github.com/cosinusalpha/cosinusalpha.github.io.git gh-pages
          mkdir -p gh-pages/css-layout
          rm -rf gh-pages/css-layout/*
          cp -r dist/* gh-pages/css-layout/
          cd gh-pages
          git add .
          if git diff --cached --quiet; then
            echo "No changes to deploy."; exit 0;
          fi
          git commit -m "Deploy css-layout from ${GITHUB_SHA::7}" || true
          git push
